---
#########Stopping App services###############
- name: copy the powershell files to local system
  win_copy:
    src: script/powershell.ps1
    dest: C:\temp\powershell.ps1
    
- name: Getting the list of services which are running
  win_shell: C:\temp\powershell.ps1
  register: running_services
  
- name: setting a variable to create powershell script
  set_fact:
    services_list: "{{running_services.stdout_lines | list }}"
    
- name: Stopping the services in the list
  win_shell: sc.exe stop "{{item}}"
  register: Stopped_services
  loop: "{{running_services.stdout_lines.split(',') | trim }}"
  delegate_to: "{{app_server}}" 
    
- name: Waiting for the all the services to be stopped
  wait_for:
    timeout: 30
  delegate_to: "{{app_server}}"


###################Stopping SQL Service#######################
- name: stopping sql service
  win_service:
    name: "{{item}}"
    state: stopped
  register: sql_service_stopped
  with_items:
  - "sql_service"
  delegate_to: "{{db_server}}"
  
- name: Waiting for sql service to be stopped
  wait_for:
    timeout: 20
  delegate_to: "{{db_server}}"

###############Rebooting App Server###########################################
- name: Restarting app server 
  win_reboot:
    reboot_timeout: 800
  register: app_server_restarted
  delegate_to: "{{app_server}}"
  
######################Rebooting DB Server##############################
- name: Restarting db server
  win_reboot:
    reboot_timeout: 800
  register: db_server_restarted
  delegate_to: "{{db_server}}"
  
######################Starting SQL service##################
- name: starting sql service
  win_service:
    name: "{{item}}"
    state: started
  register: sql_service_started
  with_items:
  - "sql_service"
  delegate_to: "{{db_server}}"

- name: Waiting for sql service to be started
  wait_for:
    timeout: 20
  delegate_to: "{{db_server}}"

###########################Starting App Services##########################
  
- name: Starting the services in the list
  win_shell: sc.exe start "{{item}}"
  register: started_services
  loop: "{{running_services.stdout_lines.split(',') | trim }}"
  delegate_to: "{{app_server}}"
  
- name: Waiting for the all the services to be started
  wait_for:
    timeout: 30
  delegate_to: "{{app_server}}"
